package hisilicon

import "unsafe"

/* Ioctl Definitions */
const HI_ID_MODULE uintptr = 0x2
const MAX_MODULE_NAME int = 16

var (
	CMD_ADD_MODULE_INFO = IoRW(HI_ID_MODULE, IOC_MODULE_CMD_ADD_INFO, unsafe.Sizeof(MODULE_INFO_S{}))
	CMD_DEL_MODULE_INFO = IoW(HI_ID_MODULE, IOC_MODULE_CMD_DEL_INFO, unsafe.Sizeof(MODULE_INFO_S{}))
	CMD_GET_MODULE_INFO = IoRW(HI_ID_MODULE, IOC_MODULE_CMD_GET_INFO, unsafe.Sizeof(MODULE_INFO_S{}))
	CMD_SET_MODULE_FUNC = IoW(HI_ID_MODULE, IOC_MODULE_CMD_SET_FUNC, unsafe.Sizeof(MODULE_INFO_S{}))
	CMD_GET_MODULE_FUNC = IoR(HI_ID_MODULE, IOC_MODULE_CMD_GET_FUNC, unsafe.Sizeof(MODULE_INFO_S{}))
	CMD_MEM_ADD_INFO    = IoW(HI_ID_MODULE, IOC_MODULE_CMD_MEM_ADD, unsafe.Sizeof(MODULE_MEM_INFO_S{}))
	CMD_MEM_DEL_INFO    = IoW(HI_ID_MODULE, IOC_MODULE_CMD_MEM_DEL, unsafe.Sizeof(MODULE_MEM_INFO_S{}))
	CMD_ALLOC_MODULE_ID = IoRW(HI_ID_MODULE, IOC_MODULE_CMD_ALLOC_ID, unsafe.Sizeof(MODULE_ALLOC_S{}))
)

type IOC_MODULE_CMD_E = uintptr

const (
	IOC_MODULE_CMD_SET_COUNT IOC_MODULE_CMD_E = iota
	IOC_MODULE_CMD_ADD_INFO
	IOC_MODULE_CMD_DEL_INFO
	IOC_MODULE_CMD_GET_INFO
	IOC_MODULE_CMD_SET_FUNC
	IOC_MODULE_CMD_GET_FUNC
	IOC_MODULE_CMD_MEM_ADD
	IOC_MODULE_CMD_MEM_DEL
	IOC_MODULE_CMD_ALLOC_ID
	IOC_MODULE_CMD_BUTT
)

/* Structs Definitions */
type MODULE_ALLOC_S struct {
	u32ModuleID  HI_U32
	u8ModuleName [MAX_MODULE_NAME + 12]HI_U8
	s32Status    HI_S32
}

type MODULE_INFO_S struct {
	u32ModuleID  HI_U32
	u8ModuleName [MAX_MODULE_NAME + 12]HI_U8
	pFnCallback  uintptr
	s32RegCount  HI_S32
	pFile        *HI_U32
}

type MODULE_MEM_INFO_S struct {
	u32ModuleID      HI_U32
	u32SizeUsrMem    HI_U32
	u32SizeKernelMem HI_U32
	u32SizeMMZ       HI_U32
	u32MaxMemSize    HI_U32
}
